---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dynamodb
  labels:
    name: dynamodb
    app: dynamodb
spec:
  serviceName: "dynamodb"
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
      labels:
        name: dynamodb
        app: dynamodb
    spec:
      containers:
        - image: saidsef/aws-dynamodb-local
          imagePullPolicy: Always
          name: dynamodb
          ports:
            - protocol: TCP
              containerPort: 8000
              name: dynamodb
          volumeMounts:
            - name: dynamodb-storage
              mountPath: /data
              subPath: data
          livenessProbe:
            tcpSocket:
                port: 8000
      volumes:
        - name: dynamodb-storage
          emptyDir: {}
